export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-24 text-white">
      <h1 className="text-4xl font-semibold mb-8">Privacy Policy</h1>

      <div className="prose prose-invert max-w-none text-gray-300">
        {/* TITLE: Privacy Policy – Genie by Social Bevy
URL TO CREATE: https://socialbevy.com/genie-privacy-policy
 
Privacy Policy for Genie by Social Bevy
Last updated: December 2025

Genie by Social Bevy (“Genie,” “we,” “us,” or “our”) is an AI-powered social concierge that interacts with users on Facebook Pages, Facebook Groups, and other Social Bevy platforms. This Privacy Policy describes how we collect, use, store, and protect information when users engage with Genie.
By using Genie, you agree to the terms described in this Privacy Policy.
 

1. Information We Collect
1.1 Information You Provide
When you interact with Genie on Facebook Pages or Facebook Groups, we may receive:
•	Comments you post
•	Replies you write to Genie
•	Any text you submit starting with “Hey Genie…” or similar triggers
Genie only receives the content required for responding.
We do NOT collect:
•	Your phone number
•	Your email address
•	Your private messages
•	Your location unless you include it in your comment
 

2. How We Use Information
We use the information you provide for:
•	Generating AI-powered responses to your questions
•	Understanding the type of recommendation you requested
•	Improving Genie’s relevance, quality, and user experience
•	Internal analytics (e.g., popularity of requests, response performance)
We do NOT:
•	Sell your data
•	Rent your data
•	Share your data with advertisers
•	Use your comment text for targeting ads
Genie’s responses are generated by AI through the Social Bevy backend and trusted service partners (such as OpenAI and Make.com).
 



3. Data Storage & Retention
We only store minimal data necessary to operate Genie, such as:
•	The text of your request
•	Timestamp of the interaction
•	Basic metadata
This data may be temporarily retained for performance analysis and improvements.
You may request data deletion at any time.
 

4. Third-Party Services
Genie interacts with the following systems:
•	Facebook/Meta – For receiving comments and posting responses
•	Make.com – For automation workflows
•	Xano – For storing and processing preference/venue data
•	OpenAI – For generating responses
These partners process data only as required to provide the Genie service.
 

5. Children’s Privacy
Genie is not intended for individuals under the age of 13.
We do not knowingly collect or store data from minors.
 

6. Data Security
We use industry-standard security measures to protect your information, including:
•	Encrypted data transmission
•	Secure server environments
•	Limited access controls
While no digital system is 100% secure, we take reasonable steps to safeguard your data.
 

7. Your Rights
You may request:
•	Access to your data
•	Deletion of your data
•	Correction of inaccurate information
To request data removal, contact:
privacy@socialbevy.com
 

8. Updates to This Policy
We may revise this Privacy Policy as Genie evolves.
Changes will be posted on this page with a new “Last Updated” date.
 
9. Contact Us
If you have questions, contact us at:
privacy@socialbevy.com
Social Bevy, Inc.

*/}
      </div>
    </main>
  );
}
