export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-24 bg-white text-black">
      <h1 className="text-4xl font-semibold mb-2">Privacy Policy</h1>
      <p className="text-sm text-gray-500 mb-12">Last updated: December 2025</p>

      <p className="text-base text-black mb-12 leading-relaxed">
        Genie by Social Bevy ("Genie," "we," "us," or "our") is an AI-powered social concierge 
        that interacts with users on Facebook Pages, Facebook Groups, and other Social Bevy 
        platforms. This Privacy Policy describes how we collect, use, store, and protect 
        information when users engage with Genie. By using Genie, you agree to the terms 
        described in this Privacy Policy.
      </p>

      {/* Section 1 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">1. Information We Collect</h2>
        <h3 className="text-base font-semibold text-black mb-2">1.1 Information You Provide</h3>
        <p className="text-base text-black mb-3 leading-relaxed">
          When you interact with Genie on Facebook Pages or Facebook Groups, we may receive:
        </p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li>Comments you post</li>
          <li>Replies you write to Genie</li>
          <li>Any text you submit starting with "Hey Genie…" or similar triggers</li>
        </ul>
        <p className="text-base text-black mb-3 leading-relaxed">
          Genie only receives the content required for responding.
        </p>
        <p className="text-base text-black mb-3 leading-relaxed">We do NOT collect:</p>
        <ul className="list-disc list-inside text-black space-y-2 pl-4">
          <li>Your phone number</li>
          <li>Your email address</li>
          <li>Your private messages</li>
          <li>Your location unless you include it in your comment</li>
        </ul>
      </section>

      {/* Section 2 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">2. How We Use Information</h2>
        <p className="text-base text-black mb-3 leading-relaxed">
          We use the information you provide for:
        </p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li>Generating AI-powered responses to your questions</li>
          <li>Understanding the type of recommendation you requested</li>
          <li>Improving Genie's relevance, quality, and user experience</li>
          <li>Internal analytics (e.g., popularity of requests, response performance)</li>
        </ul>
        <p className="text-base text-black mb-3 leading-relaxed">We do NOT:</p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li>Sell your data</li>
          <li>Rent your data</li>
          <li>Share your data with advertisers</li>
          <li>Use your comment text for targeting ads</li>
        </ul>
        <p className="text-base text-black leading-relaxed">
          Genie's responses are generated by AI through the Social Bevy backend and trusted 
          service partners (such as OpenAI and Make.com).
        </p>
      </section>

      {/* Section 3 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">3. Data Storage & Retention</h2>
        <p className="text-base text-black mb-3 leading-relaxed">
          We only store minimal data necessary to operate Genie, such as:
        </p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li>The text of your request</li>
          <li>Timestamp of the interaction</li>
          <li>Basic metadata</li>
        </ul>
        <p className="text-base text-black mb-3 leading-relaxed">
          This data may be temporarily retained for performance analysis and improvements.
        </p>
        <p className="text-base text-black leading-relaxed">
          You may request data deletion at any time.
        </p>
      </section>

      {/* Section 4 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">4. Third-Party Services</h2>
        <p className="text-base text-black mb-3 leading-relaxed">
          Genie interacts with the following systems:
        </p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li><span className="font-semibold">Facebook/Meta</span> – For receiving comments and posting responses</li>
          <li><span className="font-semibold">Make.com</span> – For automation workflows</li>
          <li><span className="font-semibold">Xano</span> – For storing and processing preference/venue data</li>
          <li><span className="font-semibold">OpenAI</span> – For generating responses</li>
        </ul>
        <p className="text-base text-black leading-relaxed">
          These partners process data only as required to provide the Genie service.
        </p>
      </section>

      {/* Section 5 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">5. Children's Privacy</h2>
        <p className="text-base text-black mb-3 leading-relaxed">
          Genie is not intended for individuals under the age of 13.
        </p>
        <p className="text-base text-black leading-relaxed">
          We do not knowingly collect or store data from minors.
        </p>
      </section>

      {/* Section 6 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">6. Data Security</h2>
        <p className="text-base text-black mb-3 leading-relaxed">
          We use industry-standard security measures to protect your information, including:
        </p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li>Encrypted data transmission</li>
          <li>Secure server environments</li>
          <li>Limited access controls</li>
        </ul>
        <p className="text-base text-black leading-relaxed">
          While no digital system is 100% secure, we take reasonable steps to safeguard your data.
        </p>
      </section>

      {/* Section 7 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">7. Your Rights</h2>
        <p className="text-base text-black mb-3 leading-relaxed">You may request:</p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li>Access to your data</li>
          <li>Deletion of your data</li>
          <li>Correction of inaccurate information</li>
        </ul>
        <p className="text-base text-black leading-relaxed">
          To request data removal, contact:{' '}
          <a href="mailto:privacy@socialbevy.com" className="text-red-600 underline hover:text-red-800">privacy@socialbevy.com</a>
        </p>
      </section>

      {/* Section 8 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">8. Updates to This Policy</h2>
        <p className="text-base text-black leading-relaxed">
          We may revise this Privacy Policy as Genie evolves. Changes will be posted on this 
          page with a new "Last Updated" date.
        </p>
      </section>

      {/* Section 9 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">9. Contact Us</h2>
        <p className="text-base text-black leading-relaxed">
          If you have questions, contact us at:{' '}
          <a href="mailto:privacy@socialbevy.com" className="text-red-600 underline hover:text-red-800">privacy@socialbevy.com</a>
        </p>
        <p className="text-base text-black mt-2">Social Bevy, Inc.</p>
      </section>
    </main>
  )
}