export default function TermsPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-24 text-white">
      <h1 className="text-4xl font-semibold mb-8">Terms of Service</h1>

      <div className="prose prose-invert max-w-none text-gray-300">
        {/* TITLE: Terms of Service – Genie by Social Bevy
URL TO CREATE: https://socialbevy.com/genie-terms
 
Terms of Service – Genie by Social Bevy
Last updated: December 2025

These Terms of Service (“Terms”) govern your use of Genie by Social Bevy (“Genie”).
By interacting with Genie, you agree to these Terms.
 

1. Description of Service
Genie is an AI-powered social concierge that delivers entertainment, dining, event, and experience recommendations based on user comments posted on Facebook Pages, Facebook Groups, and the Social Bevy ecosystem.
Genie is designed for informational purposes only and does not guarantee accuracy, availability, or safety of the venues or suggestions provided.
 

2. Acceptable Use
You agree to:
•	Use Genie respectfully
•	Not misuse or abuse the comment system
•	Not attempt to manipulate or interfere with Genie’s operation
You may not use Genie for:
•	Illegal activity
•	Spam
•	Hate speech
•	Harassment
•	Data extraction
 

3. AI-Generated Content
Genie’s responses are generated by artificial intelligence.
Responses may be:
•	Imperfect
•	Incomplete
•	Based on limited information
Social Bevy is not liable for decisions made based on Genie’s responses.
 

4. Data Handling
Interaction with Genie may involve the processing of text you submit.
See our Privacy Policy for full details:
https://socialbevy.com/genie-privacy-policy
 

5. Limitation of Liability
Social Bevy is not responsible for:
•	Venue availability
•	Pricing changes
•	Safety conditions
•	Incorrect or outdated recommendations
•	Any damages resulting from the use of Genie
Use Genie at your own discretion.
 

6. Modification of Terms
We may modify these Terms at any time.
Updates will be posted on this page with the revised date.
 

7. Contact
For questions, contact:
support@socialbevy.com

 */}
      </div>
    </main>
  );
}
