export default function TermsPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-24 bg-white text-black">
      <h1 className="text-4xl font-semibold mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-12">Last updated: December 2025</p>

      <p className="text-base text-black mb-12 leading-relaxed">
        These Terms of Service ("Terms") govern your use of Genie by Social Bevy ("Genie"). 
        By interacting with Genie, you agree to these Terms.
      </p>

      {/* Section 1 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">1. Description of Service</h2>
        <p className="text-base text-black leading-relaxed">
          Genie is an AI-powered social concierge that delivers entertainment, dining, event, and 
          experience recommendations based on user comments posted on Facebook Pages, Facebook Groups, 
          and the Social Bevy ecosystem. Genie is designed for informational purposes only and does 
          not guarantee accuracy, availability, or safety of the venues or suggestions provided.
        </p>
      </section>

      {/* Section 2 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">2. Acceptable Use</h2>
        <p className="text-base text-black mb-3 leading-relaxed">You agree to:</p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li>Use Genie respectfully</li>
          <li>Not misuse or abuse the comment system</li>
          <li>Not attempt to manipulate or interfere with Genie's operation</li>
        </ul>
        <p className="text-base text-black mb-3 leading-relaxed">You may not use Genie for:</p>
        <ul className="list-disc list-inside text-black space-y-2 pl-4">
          <li>Illegal activity</li>
          <li>Spam</li>
          <li>Hate speech</li>
          <li>Harassment</li>
          <li>Data extraction</li>
        </ul>
      </section>

      {/* Section 3 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">3. AI-Generated Content</h2>
        <p className="text-base text-black mb-3 leading-relaxed">
          Genie's responses are generated by artificial intelligence. Responses may be:
        </p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li>Imperfect</li>
          <li>Incomplete</li>
          <li>Based on limited information</li>
        </ul>
        <p className="text-base text-black leading-relaxed">
          Social Bevy is not liable for decisions made based on Genie's responses.
        </p>
      </section>

      {/* Section 4 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">4. Data Handling</h2>
       <p className="text-base text-black leading-relaxed">
  Interaction with Genie may involve the processing of text you submit. See our{' '}
  <a href="https://socialbevy.com/genie-privacy-policy" className="text-red-600 underline hover:text-red-800">Privacy Policy</a>{' '}
  for full details.
</p>
      </section>

      {/* Section 5 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">5. Limitation of Liability</h2>
        <p className="text-base text-black mb-3 leading-relaxed">
          Social Bevy is not responsible for:
        </p>
        <ul className="list-disc list-inside text-black space-y-2 mb-6 pl-4">
          <li>Venue availability</li>
          <li>Pricing changes</li>
          <li>Safety conditions</li>
          <li>Incorrect or outdated recommendations</li>
          <li>Any damages resulting from the use of Genie</li>
        </ul>
        <p className="text-base text-black leading-relaxed">
          Use Genie at your own discretion.
        </p>
      </section>

      {/* Section 6 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">6. Modification of Terms</h2>
        <p className="text-base text-black leading-relaxed">
          We may modify these Terms at any time. Updates will be posted on this page with the 
          revised date.
        </p>
      </section>

      {/* Section 7 */}
      <section className="mb-10">
        <h2 className="text-xl font-semibold text-black mb-3">7. Contact</h2>
        <p className="text-base text-black leading-relaxed">
          For questions, contact:{' '}
          
            <a href="mailto:support@socialbevy.com" className="text-red-600 underline hover:text-red-800">support@socialbevy.com</a>
        </p>
      </section>
    </main>
  )
}